timeout: 1s
network: tcp
web-01:
  host: 118.190.3.55 # ip地址
  port: 22 # 端口
  username: yejianfeng # 用户名
  password: "123456" # 密码
web-02:
  network: tcp
  host: localhost # ip地址
  port: 3306 # 端口
  username: jianfengye # 用户名
  rsa_key: "/Users/user/.ssh/id_rsa" # 私钥地址
  known_hosts: "/Users/user/.ssh/known_hosts" # 负责安全验证