url: http://127.0.0.1:8066

swagger_open: true

swagger: true

dev_fresh: 1

path:
  storage: "/Users/linglingdai/go/src/webgo/storage/"
  log: ""
  pid: ""
  cache: ""

dev: # 调试模式
  port: 8070 # 调试模式最终监听的端口，默认为8070
  backend: # 后端调试模式配置
    refresh_time: 3  # 调试模式后端更新时间，如果文件变更，等待3s才进行一次更新，能让频繁保存变更更为顺畅, 默认1s
    port: 8072 # 后端监听端口，默认8072
    monitor_folder: "" # 监听文件夹地址，为空或者不填默认为AppFolder
  frontend: # 前端调试模式配置
    port: 8071 # 前端监听端口, 默认8071

smtp:
  host: "smtp.163.com"
  port: 25
  from: "dailingling_0@163.com"
  username: "dailingling_0@163.com"
  password: "ERUIJHJSKRQRABPD"